services:
  server:
    build:
      dockerfile: Dockerfile
    container_name: server
    command: "npm run start"
    ports:
      - "3000:3000"
    environment:
      SERVER_PORT: 3000
      POSTGRES_HOST: pgdb
      POSTGRES_USER: gaz
      POSTGRES_DB: cybergaz
      POSTGRES_PASSWORD: cybergaz
      POSTGRES_PORT: 5432
    depends_on:
      pgdb:
        condition: service_healthy
